version: "3.9"

services:
  web:
    build: .
    
    image: davidnobrega/glot:latest
    # ou use "build: ." se quiser construir localmente

    command: /bin/sh -c "\
      cd /app && \
      git pull || echo 'Falha no pull' && \
      pip install --no-cache-dir -r /app/requirements.txt && \
      python manage.py migrate && \
      python manage.py collectstatic --noinput --ignore=admin && \
      celery -A core worker -l info & \
      celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler & \
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120"


    volumes:
      - media_volume:/app/media
      - static_volume:/app/static

    networks:
      - app_network
      - traefik_public

    depends_on:
      - postgres
      - rabbitmq

    restart: always

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure

      labels:
        - traefik.enable=true
        # Rota Django
        - traefik.http.routers.web.rule=Host(`django.carlosecelsoimoveis.com.br`)
        - traefik.http.services.web.loadbalancer.server.port=8000
        - traefik.http.routers.web.entrypoints=websecure
        - traefik.http.routers.web.tls=true
        - traefik.http.routers.web.tls.certresolver=le

volumes:
  media_volume:
  static_volume:

networks:
  traefik_public:
    external: true
  app_network:
    external: true
