version: "3.9"

services:
  web:
    image: davidnobrega/glot:latest

    ports:
      - "8000:8000"

    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - ENVIRONMENT=production
      - GIT_COMMIT=${GIT_COMMIT}
      - RUN_MIGRATIONS=true

    volumes:
      - configuration:/app/configuration
      - logs:/app/logs
      - media_compartilhada:/app/media
      - static_volume:/app/static

    networks:
      - app_network
      - npm_public

    depends_on:
      - postgres
      - rabbitmq

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  worker_empreendimentos:
    image: davidnobrega/glot:latest

    command: celery -A core worker -Q empreendimentos -l info

    volumes:
      - configuration:/app/configuration
      - logs:/app/logs
      - media_compartilhada:/app/media

    networks:
      - app_network

    depends_on:
      - rabbitmq

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  worker_mensagens:
    image: davidnobrega/glot:latest

    command: celery -A core worker -Q mensagens -l info

    volumes:
      - configuration:/app/configuration
      - logs:/app/logs
      - media_compartilhada:/app/media

    networks:
      - app_network

    depends_on:
      - rabbitmq

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  beat:
    image: davidnobrega/glot:latest

    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

    volumes:
      - configuration:/app/configuration
      - logs:/app/logs
      - celerybeat:/app/celerybeat

    networks:
      - app_network

    depends_on:
      - rabbitmq

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  flower:
    image: davidnobrega/glot:latest

    command: celery -A core flower --port=5555

    ports:
      - "5555:5555"

    volumes:
      - configuration:/app/configuration
      - logs:/app/logs

    networks:
      - app_network

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  configuration:
    external: true

  logs:
    external: true

  media_compartilhada:
    external: true

  static_volume:
    external: true

  celerybeat:
    external: true

networks:
  app_network:
    external: true

  npm_public:
    external: true