# Generated by Django 5.2.7 on 2026-01-21 21:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Contrato')),
                ('texto', ckeditor.fields.RichTextField(verbose_name='Texto do Contrato')),
                ('tipo', models.CharField(choices=[('aluguel', 'Contrato de Aluguel'), ('outros', 'Outros Papeis'), ('reserva', 'Contrato de Reserva'), ('venda', 'Contrato de Venda')], max_length=50)),
                ('versao', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
