# Generated by Django 5.2.7 on 2026-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='texto',
            field=models.TextField(verbose_name='Texto do Contrato'),
        ),
    ]
