# Generated by Django 5.2.7 on 2026-01-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_contrato_texto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contrato',
            new_name='CadastroDocumento',
        ),
    ]
