# Generated by Django 5.2.7 on 2026-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_rename_contrato_cadastrodocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastrodocumento",
            name="variaveis_disponiveis",
            field=models.TextField(blank=True, verbose_name="Variáveis disponíveis"),
        ),
        migrations.AlterField(
            model_name="cadastrodocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("proposta", "Proposta"),
                    ("contrato", "Contrato"),
                    ("distrato", "Distrato"),
                    ("distrato_inadimp", "Distrato por Inadimplência"),
                    ("cessao", "Cessão"),
                    ("aluguel", "Contrato de Aluguel"),
                    ("outros", "Outros Papeis"),
                    ("reserva", "Contrato de Reserva"),
                    ("venda", "Contrato de Venda"),
                ],
                max_length=50,
            ),
        ),
    ]
