# Generated by Django 5.2.7 on 2026-06-09 21:17

from django.db import migrations


def migra_tipos(apps, schema_editor):
	CadastroDocumento = apps.get_model("documentos", "CadastroDocumento")

	# id=1 → documento usado em proposta() e propostaRascunho()
	CadastroDocumento.objects.filter(id=1).update(tipo="proposta")

	# id=2 → documento usado em proposta_pdf()
	CadastroDocumento.objects.filter(id=2).update(tipo="contrato")


def reverte_tipos(apps, schema_editor):
	CadastroDocumento = apps.get_model("documentos", "CadastroDocumento")
	CadastroDocumento.objects.filter(id__in=[1, 2]).update(tipo="reserva")


class Migration(migrations.Migration):

	dependencies = [
		("documentos", "0004_refatora_cadastro_documento"),
	]

	operations = [
		migrations.RunPython(migra_tipos, reverte_tipos),
	]
