# Generated by Django 5.2.7 on 2026-06-10 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0027_remove_tabelas_endereco_conjuge"),
        ("documentos", "0005_migra_tipos_proposta_contrato"),
        ("empreendimentos", "0056_alter_lote_situacao"),
        ("vendas", "0059_registervenda_aceite_proposta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariavelDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("conjuge", "Cônjuge"),
                            ("empreendimento", "Empreendimento"),
                            ("lote", "Lote / Quadra"),
                            ("venda", "Venda"),
                            ("distrato", "Distrato"),
                            ("sistema", "Sistema"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tag_slug", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("exemplo", models.CharField(blank=True, max_length=200)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Variável de documento",
                "verbose_name_plural": "Variáveis de documento",
                "ordering": ["categoria", "ordem", "label"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="documentos/logos/"
                    ),
                ),
                ("logo_largura", models.PositiveSmallIntegerField(default=120)),
                ("cabecalho_html", models.TextField(blank=True)),
                ("rodape_html", models.TextField(blank=True)),
                ("margem_sup", models.PositiveSmallIntegerField(default=25)),
                ("margem_inf", models.PositiveSmallIntegerField(default=20)),
                ("margem_esq", models.PositiveSmallIntegerField(default=30)),
                ("margem_dir", models.PositiveSmallIntegerField(default=20)),
                (
                    "fonte_familia",
                    models.CharField(default="Times New Roman", max_length=50),
                ),
                ("fonte_tamanho", models.PositiveSmallIntegerField(default=12)),
                (
                    "empreendimento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_documento",
                        to="empreendimentos.empreendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de documento",
                "verbose_name_plural": "Configurações de documento",
            },
        ),
        migrations.CreateModel(
            name="Distrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                ("data_distrato", models.DateField()),
                (
                    "valor_devolucao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "percentual_retencao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("rascunho", "Rascunho"), ("concluido", "Concluído")],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distratos",
                        to="vendas.registervenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distrato",
                "verbose_name_plural": "Distratos",
                "ordering": ["-criado_em"],
                "permissions": [("concluir_distrato", "Pode concluir distrato")],
            },
        ),
        migrations.CreateModel(
            name="ModeloDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("distrato", "Distrato"),
                            ("proposta", "Proposta"),
                            ("reserva", "Reserva"),
                            ("declaracao", "Declaração"),
                            ("recibo", "Recibo"),
                            ("termo_aditivo", "Termo Aditivo"),
                            ("notificacao", "Notificação"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                ("conteudo_html", models.TextField(blank=True)),
                ("eh_global", models.BooleanField(default=False)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de documento",
                "verbose_name_plural": "Modelos de documento",
                "ordering": ["tipo", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("modelo_versao_snapshot", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=255)),
                ("conteudo_final_html", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("processando", "Processando"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                            ("substituido", "Substituído"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("hash_conteudo", models.CharField(blank=True, max_length=64)),
                (
                    "arquivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos/pdf/%Y/%m/"
                    ),
                ),
                (
                    "arquivo_word",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos/word/%Y/%m/"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="documentos.distrato",
                    ),
                ),
                (
                    "substitui",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substituido_por",
                        to="documentos.documentogerado",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="vendas.registervenda",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentos.modelodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento gerado",
                "verbose_name_plural": "Documentos gerados",
                "ordering": ["-criado_em"],
                "permissions": [
                    ("finalizar_documentogerado", "Pode finalizar documento"),
                    ("cancelar_documentogerado", "Pode cancelar documento"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModeloDocumentoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("versao", models.PositiveIntegerField()),
                ("conteudo_html", models.TextField()),
                ("editado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "editado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="documentos.modelodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de modelo",
                "verbose_name_plural": "Históricos de modelo",
                "ordering": ["-versao"],
            },
        ),
        migrations.CreateModel(
            name="SequencialDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
                ("ano", models.PositiveSmallIntegerField()),
                ("ultimo", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sequencial de documento",
                "verbose_name_plural": "Sequenciais de documento",
                "unique_together": {("tipo", "ano")},
            },
        ),
        migrations.CreateModel(
            name="EmpreendimentoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("padrao", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "empreendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_config",
                        to="empreendimentos.empreendimento",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empreendimentos_vinculo",
                        to="documentos.modelodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo empreendimento/modelo",
                "verbose_name_plural": "Vínculos empreendimento/modelo",
                "ordering": ["modelo__tipo", "ordem"],
                "unique_together": {("empreendimento", "modelo")},
            },
        ),
    ]
