# Generated by Django 5.2.7 on 2026-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0010_migra_cadastro_para_modelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentogerado",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("processando", "Processando"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                    ("substituido", "Substituído"),
                    ("erro", "Erro"),
                ],
                default="rascunho",
                max_length=20,
            ),
        ),
    ]
