# Generated by Django 5.2.7 on 2026-07-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0016_add_uuid_empreendimentodocumento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentogerado",
            name="distrato",
        ),
        migrations.DeleteModel(
            name="Distrato",
        ),
    ]
