# Generated by Django 5.1.2 on 2025-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('A', 'ADMINISTRADOR'), ('C', 'CORRETOR'), ('P', 'PROPRIETARIO')], max_length=1),
        ),
    ]
