# Generated by Django 5.1.2 on 2025-04-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
