# Generated by Django 5.1.2 on 2025-04-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usuarioempreendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempreendimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
