# Generated by Django 5.2.7 on 2025-10-24 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usuarioempreendimento_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contato',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
