# Generated by Django 5.2.7 on 2025-11-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ativo',
            field=models.BooleanField(default=False),
        ),
    ]
