# Generated by Django 5.2.7 on 2025-11-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ativo',
        ),
    ]
