# Generated by Django 5.2.7 on 2025-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_is_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('CORRETOR', 'CORRETOR'), ('PROPRIETARIO', 'PROPRIETARIO')], max_length=13),
        ),
    ]
