# Generated by Django 5.1.2 on 2025-03-05 20:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empreendimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterVenda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_venda', models.CharField(choices=[('CANCELADA', 'CANCELADA'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100)),
                ('dt_reserva', models.DateField(verbose_name=datetime.datetime(2025, 3, 10, 17, 51, 1, 539677))),
                ('dt_venda', models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 5, 17, 51, 1, 539677))),
                ('create_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_ativo', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_venda', to='empreendimentos.lote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_myapp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registrar Venda',
                'verbose_name_plural': 'Registrar Venda',
                'ordering': ['-id'],
            },
        ),
    ]
