# Generated by Django 5.1.2 on 2025-03-05 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateField(verbose_name=datetime.datetime(2025, 3, 10, 17, 54, 25, 966475)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 5, 17, 54, 25, 966475)),
        ),
    ]
