# Generated by Django 5.1.2 on 2025-03-05 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_registervenda_dt_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateField(verbose_name=datetime.datetime(2025, 3, 10, 18, 20, 12, 699086)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 5, 18, 20, 12, 699086)),
        ),
    ]
