# Generated by Django 5.1.2 on 2025-03-06 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_alter_registervenda_dt_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateField(verbose_name=datetime.datetime(2025, 3, 11, 18, 46, 8, 679715)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 6, 18, 46, 8, 679715)),
        ),
    ]
