# Generated by Django 5.1.2 on 2025-03-07 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_alter_registervenda_dt_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateField(verbose_name=datetime.datetime(2025, 3, 12, 7, 57, 46, 631763)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 7, 7, 57, 46, 631763)),
        ),
    ]
