# Generated by Django 5.1.2 on 2025-03-08 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_alter_registervenda_dt_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 11, 38, 40, 912261)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 11, 38, 40, 912261)),
        ),
    ]
