# Generated by Django 5.1.2 on 2025-03-08 20:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_documento'),
        ('empreendimentos', '0003_alter_lote_situacao'),
        ('vendas', '0019_alter_registervenda_dt_reserva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 17, 47, 56, 934439)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 17, 47, 56, 934439)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='lote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_venda', to='empreendimentos.lote'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
