# Generated by Django 5.1.2 on 2025-03-08 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0020_alter_registervenda_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 17, 53, 51, 618319)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 17, 53, 51, 618319)),
        ),
    ]
