# Generated by Django 5.1.2 on 2025-03-08 21:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0021_alter_registervenda_dt_reserva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 18, 1, 33, 647981)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 18, 1, 33, 647981)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
