# Generated by Django 5.1.2 on 2025-03-08 21:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_documento'),
        ('vendas', '0022_alter_registervenda_dt_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 18, 23, 37, 191189)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 8, 18, 23, 37, 191189)),
        ),
    ]
