# Generated by Django 5.1.2 on 2025-03-10 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0024_alter_registervenda_dt_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 10, 12, 31, 3, 848661)),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='dt_venda',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 10, 12, 31, 3, 848661), null=True),
        ),
    ]
