# Generated by Django 5.1.2 on 2025-03-14 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0028_alter_registervenda_dt_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 14, 20, 0, 52, 435673)),
        ),
    ]
