# Generated by Django 5.1.2 on 2025-03-17 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0029_alter_registervenda_dt_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_reserva',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
