# Generated by Django 5.1.2 on 2025-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0030_alter_registervenda_dt_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='tipo_venda',
            field=models.CharField(choices=[('CANCELADA', 'CANCELADA'), ('EM_RESERVADO', 'EM_RESERVADO'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
