# Generated by Django 5.1.2 on 2025-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0031_alter_registervenda_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='tipo_venda',
            field=models.CharField(choices=[('CANCELADA', 'CANCELADA'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
