# Generated by Django 5.2.7 on 2026-01-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0032_alter_registervenda_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='valor_sinal',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor Sinal de Compra'),
        ),
    ]
