# Generated by Django 5.2.7 on 2026-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0033_registervenda_valor_sinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='dt_primeira_parcela',
            field=models.DateField(blank=True, null=True),
        ),
    ]
