# Generated by Django 5.2.7 on 2026-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0034_registervenda_dt_primeira_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='dt_primeira_parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Data para primeira parcela'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='valor_sinal',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor do Sinal Para Compra'),
        ),
    ]
