# Generated by Django 5.2.7 on 2026-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0035_alter_registervenda_dt_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Contrato')),
                ('texto', models.TextField(verbose_name='Texto do Contrato')),
                ('tipo', models.CharField(choices=[('venda', 'Contrato de Venda'), ('reserva', 'Contrato de Reserva')], max_length=50)),
                ('versao', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
