# Generated by Django 5.2.7 on 2026-01-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0036_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('aluguel', 'Contrato de Aluguel'), ('outros', 'Outros Papeis'), ('reserva', 'Contrato de Reserva'), ('venda', 'Contrato de Venda')], max_length=50),
        ),
    ]
