# Generated by Django 5.2.7 on 2026-01-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0037_alter_contrato_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
