# Generated by Django 5.2.7 on 2026-01-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0038_delete_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='quantidade_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registervenda',
            name='quantidade_parcelas_pagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registervenda',
            name='valor_dinanciado',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor do Sinal Para Compra'),
        ),
        migrations.AddField(
            model_name='registervenda',
            name='valor_inicio_contrato',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor do Sinal Para Compra'),
        ),
    ]
