# Generated by Django 5.2.7 on 2026-01-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0039_registervenda_quantidade_parcelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registervenda',
            name='valor_dinanciado',
        ),
        migrations.AddField(
            model_name='registervenda',
            name='valor_financiado',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor do Financiamento'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='valor_inicio_contrato',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor do ínicio do Contato'),
        ),
    ]
