# Generated by Django 5.2.7 on 2026-02-19 20:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0040_remove_registervenda_valor_dinanciado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
