# Generated by Django 5.2.7 on 2026-02-19 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0041_registervenda_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
