# Generated by Django 5.2.7 on 2026-02-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0044_registervenda_corretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='valor_inicio_contrato',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='valor_sinal',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Valor do Sinal'),
        ),
    ]
