# Generated by Django 5.2.7 on 2026-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0045_alter_registervenda_valor_inicio_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterVendaIntercalada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_parcelas_intercalada', models.IntegerField(blank=True, null=True)),
                ('valor_intercalada', models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Valor do Sinal')),
            ],
        ),
        migrations.AddField(
            model_name='registervenda',
            name='valor_entrada',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Valor do entrada'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='valor_inicio_contrato',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor do Contrato'),
        ),
    ]
