# Generated by Django 5.2.7 on 2026-03-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0046_registervendaintercalada_registervenda_valor_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='intercalada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercaladas', to='vendas.registervendaintercalada'),
        ),
        migrations.AlterField(
            model_name='registervendaintercalada',
            name='quantidade_parcelas_intercalada',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantidade de intercaladas'),
        ),
        migrations.AlterField(
            model_name='registervendaintercalada',
            name='valor_intercalada',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Valor da intercalada'),
        ),
    ]
