# Generated by Django 5.2.7 on 2026-03-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0047_registervenda_intercalada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registervenda',
            name='intercalada',
        ),
        migrations.AddField(
            model_name='registervendaintercalada',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intercaladas', to='vendas.registervenda'),
        ),
    ]
