# Generated by Django 5.2.7 on 2026-03-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0048_remove_registervenda_intercalada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='valor_financiado',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Valor do Financiamento'),
        ),
        migrations.AlterField(
            model_name='registervenda',
            name='valor_inicio_contrato',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Valor do Contrato'),
        ),
    ]
