# Generated by Django 5.2.7 on 2026-03-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0049_alter_registervenda_valor_financiado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='valor_financiado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True, verbose_name='Valor do Financiamento'),
        ),
    ]
