# Generated by Django 5.2.7 on 2026-05-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0050_alter_registervenda_valor_financiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='reajuste',
            field=models.BooleanField(default=False),
        ),
    ]
