# Generated by Django 5.2.7 on 2026-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0051_registervenda_reajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='reajuste',
            field=models.BooleanField(default=True),
        ),
    ]
