# Generated by Django 5.2.7 on 2026-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0052_alter_registervenda_reajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='valor_parcela',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Valor da parcela'),
        ),
    ]
