# Generated by Django 5.2.7 on 2026-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0053_registervenda_valor_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervenda',
            name='tipo_venda',
            field=models.CharField(choices=[('CANCELADA', 'CANCELADA'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO'), ('ANALISE', 'ANALISE')], max_length=100),
        ),
    ]
