# Generated by Django 5.2.7 on 2026-05-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0054_alter_registervenda_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='desconto',
            field=models.CharField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Desconto'),
        ),
    ]
