# Generated by Django 5.2.7 on 2026-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0055_registervenda_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registervenda',
            name='desconto',
        ),
        migrations.AddField(
            model_name='registervenda',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto'),
        ),
    ]
