# Generated by Django 5.2.7 on 2026-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0057_alter_registervenda_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervenda',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
