# Generated by Django 5.2.7 on 2026-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0059_registervenda_aceite_proposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="registervenda",
            name="corretor_nome",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
