# Generated by Django 5.2.7 on 2026-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0060_add_corretor_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registervenda",
            name="tipo_venda",
            field=models.CharField(
                choices=[
                    ("CANCELADA", "CANCELADA"),
                    ("RESERVADO", "RESERVADO"),
                    ("VENDIDO", "VENDIDO"),
                    ("ANALISE", "ANALISE"),
                    ("NAO-ACEITE", "NAO-ACEITE"),
                    ("PRE-VENDA", "PRE-VENDA"),
                ],
                max_length=100,
            ),
        ),
    ]
