# Generated by Django 5.2.7 on 2026-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0063_vendadocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendadocumento",
            name="ciclo",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="vendadocumento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("enviado", "Enviado"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                    ("arquivado", "Arquivado"),
                ],
                default="enviado",
                max_length=20,
            ),
        ),
    ]
