# Generated by Django 5.2.7 on 2026-07-02 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0014_add_variavel_qtd_parcelas_extenso"),
        ("vendas", "0064_add_ciclo_arquivado_vendadocumento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vendadocumento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "aprovado")),
                fields=("venda", "tipo"),
                name="unico_aprovado_por_venda_tipo",
            ),
        ),
    ]
