# Generated by Django 5.2.7 on 2026-07-07 12:03

import vendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0065_unico_aprovado_por_venda_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendadocumento",
            name="arquivo_assinado",
            field=models.FileField(
                upload_to="vendas/documentos_assinados/",
                validators=[vendas.models.validate_documento_assinado],
            ),
        ),
    ]
