# Generated by Django 5.2.7 on 2026-07-20 12:32

import django.db.models.deletion
import uuid
import vendas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0038_alter_representantedocumento_tipo"),
        ("documentos", "0016_add_uuid_empreendimentodocumento"),
        ("vendas", "0069_alter_registervenda_tipo_venda_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registervenda",
            name="status_transferencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRE_TRANSFERENCIA", "Pré-Transferência"),
                    ("TRANSFERENCIA_CONCLUIDA", "Transferência Concluída"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TransferenciaTitularidade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRE_TRANSFERENCIA", "Pré-Transferência"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PRE_TRANSFERENCIA",
                        max_length=20,
                    ),
                ),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("efetivado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "arquivo_termo_assinado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="vendas/termos_transferencia/",
                        validators=[vendas.models.validate_documento_assinado],
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "cliente_anterior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_como_anterior",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "cliente_novo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_como_novo",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "documento_gerado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documentos.documentogerado",
                    ),
                ),
                (
                    "efetivado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_efetivadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iniciado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_iniciadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias",
                        to="vendas.registervenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência de Titularidade",
                "verbose_name_plural": "Transferências de Titularidade",
                "ordering": ["-iniciado_em"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoTitularidade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dt_inicio", models.DateField()),
                ("dt_fim", models.DateField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_titularidade",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_titularidade",
                        to="vendas.registervenda",
                    ),
                ),
                (
                    "transferencia_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendas.transferenciatitularidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Titularidade",
                "verbose_name_plural": "Históricos de Titularidade",
                "ordering": ["venda", "dt_inicio"],
            },
        ),
        migrations.AddConstraint(
            model_name="transferenciatitularidade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PRE_TRANSFERENCIA")),
                fields=("venda",),
                name="unica_transferencia_ativa_por_venda",
            ),
        ),
    ]
