# Generated by Django 5.2.7 on 2026-07-20 12:33
#
# NAO EXECUTAR AUTOMATICAMENTE. Aguardar confirmacao antes de rodar
# `python manage.py migrate vendas 0071`.

from django.db import migrations


def popula_historico_titularidade(apps, schema_editor):
    RegisterVenda = apps.get_model("vendas", "RegisterVenda")
    HistoricoTitularidade = apps.get_model("vendas", "HistoricoTitularidade")

    vendas = RegisterVenda.objects.filter(
        cliente__isnull=False, is_ativo=True
    )
    historicos = [
        HistoricoTitularidade(
            venda=venda,
            cliente=venda.cliente,
            dt_inicio=venda.dt_venda or venda.create_at,
            dt_fim=None,
            transferencia_origem=None,
        )
        for venda in vendas
    ]
    HistoricoTitularidade.objects.bulk_create(historicos)


def reverte_historico_titularidade(apps, schema_editor):
    HistoricoTitularidade = apps.get_model("vendas", "HistoricoTitularidade")
    HistoricoTitularidade.objects.filter(transferencia_origem__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0070_adiciona_transferencia_titularidade"),
    ]

    operations = [
        migrations.RunPython(
            popula_historico_titularidade, reverte_historico_titularidade
        ),
    ]
