# Generated by Django 5.2.7 on 2026-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0071_popula_historico_titularidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendadocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("proposta_assinada", "Proposta Assinada"),
                    ("contrato_assinado", "Contrato Assinado"),
                    ("termo_transferencia", "Termo de Transferência"),
                    ("outros", "Outros"),
                ],
                default="outros",
                max_length=30,
            ),
        ),
    ]
