# Generated by Django 5.2.7 on 2026-07-20 22:30

import django.db.models.deletion
import uuid
import vendas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0017_remove_distrato_scaffold_morto"),
        ("vendas", "0072_add_termo_transferencia_tipo_vendadocumento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registervenda",
            name="status_distrato",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INICIADO", "Iniciado"),
                    ("AGUARDANDO_ASSINATURA", "Aguardando Assinatura"),
                    ("CONCLUIDO", "Concluído"),
                    ("CANCELADO", "Cancelado"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registervenda",
            name="tipo_venda",
            field=models.CharField(
                choices=[
                    ("CANCELADA", "CANCELADA"),
                    ("RESERVADO", "RESERVADO"),
                    ("VENDIDO", "VENDIDO"),
                    ("ANALISE", "ANALISE"),
                    ("NAO_ACEITE", "NAO-ACEITE"),
                    ("PRE-VENDA", "PRE-VENDA"),
                    ("DISTRATADA", "DISTRATADA"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="DistratoVenda",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INICIADO", "Iniciado"),
                            ("AGUARDANDO_ASSINATURA", "Aguardando Assinatura"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="INICIADO",
                        max_length=30,
                    ),
                ),
                ("is_administrativo", models.BooleanField(default=False)),
                ("motivo_administrativo", models.TextField(blank=True)),
                (
                    "termo_assinado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="vendas/distratos/termos/",
                        validators=[vendas.models.validate_documento_assinado],
                    ),
                ),
                ("motivo", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "concluido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distratos_concluidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento_gerado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distratos",
                        to="documentos.documentogerado",
                    ),
                ),
                (
                    "iniciado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distratos_iniciados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distratos",
                        to="vendas.registervenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distrato de Venda",
                "verbose_name_plural": "Distratos de Venda",
                "ordering": ["-criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["INICIADO", "AGUARDANDO_ASSINATURA"])
                        ),
                        fields=("venda",),
                        name="unico_distrato_ativo_por_venda",
                    )
                ],
            },
        ),
    ]
