# Generated by Django 5.2.7 on 2026-07-22 16:53

import vendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0073_distrato_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferenciatitularidade",
            name="certidao_negativa_iptu",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="vendas/certidoes_iptu/",
                validators=[vendas.models.validate_documento_assinado],
            ),
        ),
    ]
