# Generated by Django 5.2.7 on 2026-07-20 23:13

import cobranca.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empreendimentos", "0068_add_rg_novo_cnh_documento_representante"),
        ("vendas", "0073_distrato_venda"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carne",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("numero_carne", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GERADO", "Gerado"),
                            ("ENVIADO", "Enviado ao Banco"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="GERADO",
                        max_length=20,
                    ),
                ),
                ("ano_referencia", models.PositiveIntegerField()),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gerado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carnes_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carnes",
                        to="vendas.registervenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carnê",
                "verbose_name_plural": "Carnês",
                "ordering": ["-ano_referencia", "numero_carne"],
                "unique_together": {("venda", "numero_carne")},
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoGateway",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("banco_brasil", "Banco do Brasil"),
                            ("sicredi", "Sicredi"),
                            ("sicoob", "Sicoob"),
                            ("bradesco", "Bradesco"),
                            ("banco_nordeste", "Banco do Nordeste"),
                            ("caixa_economica", "Caixa Econômica Federal"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "client_id",
                    cobranca.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "client_secret",
                    cobranca.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "convenio",
                    cobranca.fields.EncryptedCharField(
                        blank=True, max_length=100, null=True
                    ),
                ),
                (
                    "certificado",
                    cobranca.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "chave_certificado",
                    cobranca.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("sandbox", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empreendimento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao_gateway",
                        to="empreendimentos.empreendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Gateway",
                "verbose_name_plural": "Configurações de Gateway",
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("PARCELA", "Parcela")],
                        default="PARCELA",
                        max_length=10,
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("BOLETO", "Boleto Bancário"),
                            ("MANUAL", "Baixa Manual"),
                        ],
                        default="BOLETO",
                        max_length=10,
                    ),
                ),
                ("numero_parcela", models.PositiveIntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "igpm_aplicado",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ENVIADA_BANCO", "Enviada ao Banco"),
                            ("PAGA", "Paga"),
                            ("CANCELADA", "Cancelada"),
                            ("INADIMPLENTE", "Inadimplente"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "baixado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcelas_baixadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "carne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcelas",
                        to="cobranca.carne",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcelas",
                        to="vendas.registervenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
                "ordering": ["venda", "numero_parcela"],
                "unique_together": {("carne", "numero_parcela")},
            },
        ),
        migrations.CreateModel(
            name="CobrancaBancaria",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("gateway", models.CharField(max_length=30)),
                (
                    "nosso_numero",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("linha_digitavel", models.TextField(blank=True, null=True)),
                ("codigo_barras", models.TextField(blank=True, null=True)),
                ("url_boleto", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("REGISTRADA", "Registrada no Banco"),
                            ("PAGA", "Paga"),
                            ("CANCELADA", "Cancelada"),
                            ("ERRO", "Erro"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("resposta_banco", models.JSONField(blank=True, null=True)),
                ("erro_mensagem", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas_bancarias",
                        to="cobranca.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobrança Bancária",
                "verbose_name_plural": "Cobranças Bancárias",
                "ordering": ["-created_at"],
            },
        ),
    ]
