# Generated by Django 5.1.2 on 2025-03-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empreendimento', verbose_name='Logo')),
                ('is_ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'empreendimento',
                'verbose_name_plural': 'Empreendimentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namequadra', models.CharField(max_length=50)),
                ('empr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empreendimento', to='empreendimentos.empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=50, verbose_name='Nome do Lote')),
                ('area', models.CharField(max_length=50, verbose_name='ÁREA')),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'DISPONIVEL'), ('RESEVADO', 'RESEVADO'), ('VENDIDO', 'VENDIDO')], max_length=100)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadra', to='empreendimentos.quadra')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['id'],
            },
        ),
    ]
