# Generated by Django 5.1.2 on 2025-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0002_empreendimento_tempo_reseva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'DISPONIVEL'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
