# Generated by Django 5.1.2 on 2025-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0003_alter_lote_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
