# Generated by Django 5.1.2 on 2025-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0004_alter_empreendimento_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'DISPONIVEL'), ('EM_RESERVADO', 'EM_RESERVADO'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
