# Generated by Django 5.1.2 on 2025-03-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0005_alter_lote_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'DISPONIVEL'), ('EM_RESERVA', 'EM_RESERVA'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
