# Generated by Django 5.1.2 on 2025-03-20 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0006_alter_lote_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='tempo_reservando',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
