# Generated by Django 5.1.2 on 2025-03-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0007_empreendimento_tempo_reservando'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empreendimento',
            old_name='tempo_reseva',
            new_name='tempo_reserva',
        ),
    ]
