# Generated by Django 5.1.2 on 2025-03-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0008_rename_tempo_reseva_empreendimento_tempo_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='tempo_reservando',
        ),
    ]
