# Generated by Django 5.1.2 on 2025-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0009_remove_empreendimento_tempo_reservando'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tempo_reservado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
