# Generated by Django 5.1.2 on 2025-03-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0010_lote_tempo_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tempo_reservado',
            field=models.DateTimeField(),
        ),
    ]
