# Generated by Django 5.1.2 on 2025-03-31 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0012_alter_lote_tempo_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tempo_reservado',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
