# Generated by Django 5.1.2 on 2025-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0013_alter_lote_tempo_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='situacao',
            field=models.CharField(choices=[('CONSTRUTORA', 'CONSTRUTORA'), ('DISPONIVEL', 'DISPONIVEL'), ('EM_RESERVA', 'EM_RESERVA'), ('INDISPONIVEL', 'INDISPONIVEL'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
