# Generated by Django 5.1.2 on 2025-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0014_alter_lote_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='valor_metro_quadrado',
            field=models.CharField(default=0.0, max_length=50, verbose_name='Valor Metro Quadrado'),
        ),
    ]
