# Generated by Django 5.1.2 on 2025-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0015_lote_valor_metro_quadrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='quantidade_parcelas',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
