# Generated by Django 5.1.2 on 2025-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0016_empreendimento_quantidade_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='quantidade_parcelas',
            field=models.IntegerField(default=0),
        ),
    ]
