# Generated by Django 5.1.2 on 2025-04-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0017_alter_empreendimento_quantidade_parcelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empreendimento',
            old_name='quantidade_parcelas',
            new_name='quantidade_parcela',
        ),
    ]
