# Generated by Django 5.1.2 on 2025-04-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0018_rename_quantidade_parcelas_empreendimento_quantidade_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='quadra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='empreendimentos.quadra'),
        ),
    ]
