# Generated by Django 5.1.2 on 2025-05-16 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0019_alter_lote_quadra'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cliente_reserva',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='lote',
            name='data_termina_reserva',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='lote',
            name='telefone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='lote',
            name='telefone_user',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='lote',
            name='user',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='lote',
            name='situacao',
            field=models.CharField(choices=[('CONSTRUTORA', 'CONSTRUTORA'), ('DISPONIVEL', 'DISPONIVEL'), ('EM_RESERVA', 'EM_RESERVA'), ('INDISPONIVEL', 'INDISPONIVEL'), ('PRE-RESERVA', 'PRE-RESERVA'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
