# Generated by Django 5.2.7 on 2025-10-24 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0020_lote_cliente_reserva_lote_data_termina_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='telefone',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='telefone_user',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
