# Generated by Django 5.2.7 on 2025-11-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0021_empreendimento_telefone_alter_lote_telefone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empreendimento',
            options={'ordering': ['id'], 'verbose_name': 'Empreendimento', 'verbose_name_plural': 'Empreendimentos'},
        ),
    ]
