# Generated by Django 5.2.7 on 2026-01-08 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0022_alter_empreendimento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cod', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DadosBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=15)),
                ('favorecido', models.CharField(max_length=100)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banco', to='empreendimentos.banco')),
            ],
            options={
                'verbose_name': 'DadosBancario',
                'verbose_name_plural': 'DadosBancarios',
                'ordering': ['banco'],
            },
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='dadosBancario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosBancario', to='empreendimentos.dadosbancario'),
        ),
    ]
