# Generated by Django 5.2.7 on 2026-01-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0023_banco_dadosbancario_empreendimento_dadosbancario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosbancario',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='dadosBancario',
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='agencia',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='banco',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='codBanco',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='conta',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='favorecido',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='DadosBancario',
        ),
    ]
