# Generated by Django 5.2.7 on 2026-01-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0024_remove_dadosbancario_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='cnpj',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
