# Generated by Django 5.2.7 on 2026-01-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0025_empreendimento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='agencia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='banco',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='codBanco',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='conta',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='favorecido',
            field=models.CharField(max_length=100),
        ),
    ]
