# Generated by Django 5.2.7 on 2026-01-09 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0026_alter_empreendimento_agencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='quantidade_parcela',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='tempo_reserva',
            field=models.IntegerField(),
        ),
    ]
