# Generated by Django 5.2.7 on 2026-01-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0028_empreendimento_bairro_empreendimento_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='cnpj',
            field=models.CharField(help_text='CNPJ (apenas números).', max_length=18, unique=True),
        ),
    ]
