# Generated by Django 5.2.7 on 2026-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0029_alter_empreendimento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='cnpj',
            field=models.CharField(help_text='CNPJ (apenas números).', max_length=18),
        ),
    ]
