# Generated by Django 5.2.7 on 2026-01-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0031_alter_empreendimento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='cnpj',
            field=models.CharField(default=2, help_text='Informe CNPJ (apenas números).', max_length=18, unique=True),
            preserve_default=False,
        ),
    ]
