# Generated by Django 5.2.7 on 2026-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0032_alter_empreendimento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='banco',
            field=models.CharField(max_length=50),
        ),
    ]
