# Generated by Django 5.2.7 on 2026-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0033_alter_empreendimento_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='banco',
            field=models.CharField(choices=[('Banco do Brasil', '001'), ('Banco do Nodeste', '004'), ('Caixa Economica', '104'), ('Sicoob', '756'), ('Sincred', '748')], max_length=100),
        ),
    ]
