# Generated by Django 5.2.7 on 2026-01-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0035_empreendimento_observacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empreendimento',
            old_name='favorecido',
            new_name='razaoSocial',
        ),
    ]
