# Generated by Django 5.2.7 on 2026-01-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0036_rename_favorecido_empreendimento_razaosocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='registroCartorio',
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='banco',
            field=models.CharField(choices=[('001', 'Banco do Brasil'), ('004', 'Banco do Nodeste'), ('104', 'Caixa Economica'), ('756', 'Sicoob'), ('748', 'Sincred')], help_text='Informe CNPJ (apenas números).', max_length=100),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
