# Generated by Django 5.2.7 on 2026-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0037_remove_empreendimento_registrocartorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='reajuste',
            field=models.TextField(blank=True, null=True),
        ),
    ]
