# Generated by Django 5.2.7 on 2026-01-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0038_empreendimento_reajuste'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpreendimentoContrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('contrato', models.TextField()),
                ('is_ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='contrato_empreendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contratos_Empreendimentos', to='empreendimentos.empreendimentocontrato'),
        ),
    ]
