# Generated by Django 5.2.7 on 2026-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0039_empreendimentocontrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimentocontrato',
            name='contrato',
            field=models.TextField(),
        ),
    ]
