# Generated by Django 5.2.7 on 2026-01-21 19:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0039_empreendimentocontrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimentocontrato',
            name='contrato',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
