# Generated by Django 5.2.7 on 2026-01-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0040_alter_empreendimentocontrato_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='contrato_empreendimento',
        ),
        migrations.DeleteModel(
            name='EmpreendimentoContrato',
        ),
    ]
