# Generated by Django 5.2.7 on 2026-01-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_rename_contrato_cadastrodocumento'),
        ('empreendimentos', '0041_remove_empreendimento_contrato_empreendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.cadastrodocumento', verbose_name='Contrato padrão'),
        ),
    ]
