# Generated by Django 5.2.7 on 2026-01-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0042_empreendimento_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='banco',
            field=models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('004', 'Banco do Nodeste'), ('104', 'Caixa Economica'), ('756', 'Sicoob'), ('748', 'Sincred')], max_length=100, verbose_name='Banco'),
        ),
    ]
