# Generated by Django 5.2.7 on 2026-01-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0043_alter_empreendimento_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='comprimento'),
        ),
        migrations.AddField(
            model_name='lote',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='largura'),
        ),
    ]
