# Generated by Django 5.2.7 on 2026-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0044_lote_comprimento_lote_largura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Informe CNPJ (apenas números).', max_length=18, null=True, unique=True),
        ),
    ]
