# Generated by Django 5.2.7 on 2026-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0045_alter_empreendimento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
