# Generated by Django 5.2.7 on 2026-02-19 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0047_alter_empreendimento_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
