# Generated by Django 5.2.7 on 2026-02-19 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0048_lote_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
