# Generated by Django 5.2.7 on 2026-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0049_alter_lote_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='dimenssoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='medidasConfrontacoes',
            field=models.TextField(blank=True),
        ),
    ]
