# Generated by Django 5.2.7 on 2026-03-31 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0050_lote_dimenssoes_lote_medidasconfrontacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
