# Generated by Django 5.2.7 on 2026-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0052_alter_empreendimento_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='tipo_correcao',
            field=models.CharField(blank=True, default='IGPM', max_length=10, null=True),
        ),
    ]
