# Generated by Django 5.2.7 on 2026-05-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0053_empreendimento_tipo_correcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='reajuste',
        ),
    ]
