# Generated by Django 5.2.7 on 2026-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0054_remove_empreendimento_reajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='desconto',
            field=models.CharField(blank=True, default='0', max_length=2, null=True, verbose_name='Desconto'),
        ),
    ]
