
# Generated by Django 5.2.7 on 2026-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0055_empreendimento_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='situacao',
            field=models.CharField(choices=[('CONSTRUTORA', 'CONSTRUTORA'), ('DISPONIVEL', 'DISPONIVEL'), ('EM_RESERVA', 'EM_RESERVA'), ('INDISPONIVEL', 'INDISPONIVEL'), ('PRE-RESERVA', 'PRE-RESERVA'), ('RESERVADO', 'RESERVADO'), ('VENDIDO', 'VENDIDO'), ('ANALISE', 'ANALISE')], max_length=100),
        ),
    ]
