# Generated by Django 5.2.7 on 2026-06-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0057_remove_empreendimento_contrato_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="empreendimento",
            name="cidade_foro",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="empreendimento",
            name="matricula",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="empreendimento",
            name="representante_cpf",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="empreendimento",
            name="representante_nome",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="empreendimento",
            name="representante_rg",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
