# Generated by Django 5.2.7 on 2026-06-19 17:32

import empreendimentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0058_add_representante_matricula_foro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empreendimento",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=empreendimentos.models._upload_logo_empreendimento,
                verbose_name="Logo",
            ),
        ),
    ]
