# Generated by Django 5.2.7 on 2026-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0059_alter_empreendimento_logo"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE empreendimentos_lote ALTER COLUMN tempo_reservado DROP DEFAULT",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE empreendimentos_lote ALTER COLUMN tempo_reservado DROP NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="UPDATE empreendimentos_lote SET tempo_reservado = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE empreendimentos_lote ALTER COLUMN tempo_reservado TYPE timestamp with time zone USING tempo_reservado::text::timestamp with time zone",
            reverse_sql="ALTER TABLE empreendimentos_lote ALTER COLUMN tempo_reservado TYPE time without time zone USING NULL",
        ),
        migrations.AlterField(
            model_name="lote",
            name="tempo_reservado",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]