# Generated by Django 5.2.7 on 2026-06-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0060_alter_lote_tempo_reservado_to_datetimefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("CONSTRUTORA", "CONSTRUTORA"),
                    ("DISPONIVEL", "DISPONIVEL"),
                    ("EM_RESERVA", "EM_RESERVA"),
                    ("INDISPONIVEL", "INDISPONIVEL"),
                    ("PRE-RESERVA", "PRE-RESERVA"),
                    ("RESERVADO", "RESERVADO"),
                    ("PRE-VENDA", "PRE-VENDA"),
                    ("VENDIDO", "VENDIDO"),
                    ("ANALISE", "ANALISE"),
                ],
                max_length=100,
            ),
        ),
    ]
