# Generated by Django 5.2.7 on 2026-07-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0061_add_pre_venda_typelote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lote",
            old_name="medidasConfrontacoes",
            new_name="confrontacoes",
        ),
    ]
