# Generated by Django 5.2.7 on 2026-07-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0062_rename_medidasconfrontacoes_lote_confrontacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="medidas",
            field=models.TextField(blank=True),
        ),
    ]
