# Generated by Django 5.2.7 on 2026-07-13 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("empreendimentos", "0063_lote_medidas"),
    ]

    operations = [
        migrations.AddField(
            model_name="empreendimento",
            name="endereco_empreendimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empreendimentos",
                to="base.endereco",
            ),
        ),
        migrations.AddField(
            model_name="empreendimento",
            name="endereco_empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas",
                to="base.endereco",
            ),
        ),
        migrations.CreateModel(
            name="RepresentanteLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("documento", models.CharField(max_length=14)),
                ("numero_rg", models.CharField(blank=True, max_length=30)),
                ("orgao_emissor_rg", models.CharField(blank=True, max_length=20)),
                ("cargo", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solteiro", "Solteiro"),
                            ("casado", "Casado"),
                            ("divorciado", "Divorciado"),
                            ("viuvo", "Viúvo"),
                            ("separado_judicialmente", "Separado judicialmente"),
                            ("uniao_estavel", "União estável"),
                        ],
                        max_length=22,
                    ),
                ),
                ("is_ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empreendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representantes",
                        to="empreendimentos.empreendimento",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="representantes",
                        to="base.endereco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Representante Legal",
                "verbose_name_plural": "Representantes Legais",
                "unique_together": {("empreendimento", "documento")},
            },
        ),
    ]
