# Generated by Django 5.2.7 on 2026-07-13 23:44

import django.db.models.deletion
import empreendimentos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0064_empreendimento_endereco_empreendimento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="representantelegal",
            name="conj_documento",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name="representantelegal",
            name="conj_nome",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="representantelegal",
            name="conj_numero_rg",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="representantelegal",
            name="conj_orgao_emissor_rg",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="DocumentoEmpreendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("contrato_social", "Contrato Social"),
                            ("matricula_imovel", "Matrícula do Imóvel"),
                            ("alvara", "Alvará"),
                            ("memorial_descritivo", "Memorial Descritivo"),
                            ("planta_loteamento", "Planta do Loteamento"),
                            ("licenca_ambiental", "Licença Ambiental"),
                            ("registro_loteamento", "Registro do Loteamento"),
                            ("procuracao", "Procuração"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        help_text="Deixe em branco para usar o nome da categoria",
                        max_length=255,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=empreendimentos.models._upload_documento_empreendimento,
                        validators=[empreendimentos.models._validate_documento_wizard],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empreendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="empreendimentos.empreendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Empreendimento",
                "verbose_name_plural": "Documentos do Empreendimento",
                "ordering": ["categoria", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoRepresentante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("rg_representante", "RG do Representante"),
                            ("cpf_representante", "CPF do Representante"),
                            ("comprovante_residencia", "Comprovante de Residência"),
                            ("procuracao", "Procuração"),
                            ("rg_conjuge", "RG do Cônjuge"),
                            ("cpf_conjuge", "CPF do Cônjuge"),
                            ("certidao_casamento", "Certidão de Casamento"),
                            ("pacto_antenupcial", "Pacto Antenupcial"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=255)),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=empreendimentos.models._upload_documento_representante,
                        validators=[empreendimentos.models._validate_documento_wizard],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "representante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="empreendimentos.representantelegal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Representante",
                "verbose_name_plural": "Documentos do Representante",
                "ordering": ["categoria", "criado_em"],
            },
        ),
    ]
