# Generated by Django 5.2.7 on 2026-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0066_documento_criado_por_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoempreendimento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("contrato_social", "Contrato Social"),
                    ("matricula_imovel", "Matrícula do Imóvel"),
                    ("alvara", "Alvará"),
                    ("memorial_descritivo", "Memorial Descritivo"),
                    ("planta_loteamento", "Planta do Loteamento"),
                    ("licenca_ambiental", "Licença Ambiental"),
                    ("registro_loteamento", "Registro do Loteamento"),
                    ("procuracao", "Procuração"),
                    ("mapa", "Mapa do Loteamento"),
                    ("tabela", "Tabela de Preços"),
                    ("outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
    ]
