# Generated by Django 5.2.7 on 2026-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0067_alter_documentoempreendimento_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentorepresentante",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("rg_representante", "RG do Representante"),
                    ("rg_novo_representante", "RG (novo modelo) do Representante"),
                    ("cnh_representante", "CNH do Representante"),
                    ("cpf_representante", "CPF do Representante"),
                    ("comprovante_residencia", "Comprovante de Residência"),
                    ("procuracao", "Procuração"),
                    ("rg_conjuge", "RG do Cônjuge"),
                    ("rg_novo_conjuge", "RG (novo modelo) do Cônjuge"),
                    ("cnh_conjuge", "CNH do Cônjuge"),
                    ("cpf_conjuge", "CPF do Cônjuge"),
                    ("certidao_casamento", "Certidão de Casamento"),
                    ("pacto_antenupcial", "Pacto Antenupcial"),
                    ("outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
    ]
