# Generated by Django 5.2.7 on 2026-07-21 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0068_add_rg_novo_cnh_documento_representante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empreendimento",
            name="nome",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="empreendimento",
            name="quantidade_parcela",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empreendimento",
            name="telefone",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.",
                        regex="^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empreendimento",
            name="tempo_reserva",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="representantelegal",
            name="cargo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="representantelegal",
            name="documento",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name="representantelegal",
            name="nome",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
