# Generated by Django 5.2.7 on 2026-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empreendimentos", "0069_wizard_campos_opcionais"),
    ]

    operations = [
        migrations.AddField(
            model_name="empreendimento",
            name="sigla",
            field=models.CharField(
                blank=True,
                help_text="Prefixo usado no número do contrato e documentos de cobrança. Se vazio, será gerado automaticamente com as iniciais do nome.",
                max_length=20,
                null=True,
                verbose_name="Sigla",
            ),
        ),
    ]
