# Generated by Django 5.2.7 on 2026-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("empreendimentos", "0070_empreendimento_sigla"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="representantelegal",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="representantelegal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("documento", ""), _negated=True),
                fields=("empreendimento", "documento"),
                name="uniq_representante_empreendimento_documento_preenchido",
            ),
        ),
    ]
