# Generated by Django 5.2.7 on 2026-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("empreendimentos", "0071_representantelegal_documento_unique_condicional"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="representantelegal",
            name="uniq_representante_empreendimento_documento_preenchido",
            constraint=models.UniqueConstraint(
                condition=models.Q(("documento", ""), _negated=True),
                fields=("empreendimento", "documento"),
                name="uniq_representante_empreendimento_documento_preenchido",
                violation_error_message="Já existe um representante com este CPF cadastrado para este empreendimento.",
            ),
        ),
    ]
