# Generated by Django 5.1.2 on 2025-03-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='phone',
            new_name='telefone',
        ),
    ]
