# Generated by Django 5.1.2 on 2025-03-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_phone_cliente_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='fone',
        ),
    ]
