# Generated by Django 5.1.2 on 2025-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_telefone_cliente_fone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default='00000000000', max_length=18),
        ),
    ]
