# Generated by Django 5.1.2 on 2025-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default='00000000000', max_length=18, unique=True),
        ),
    ]
