# Generated by Django 5.1.2 on 2025-10-23 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
