# Generated by Django 5.1.2 on 2025-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_fone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
