# Generated by Django 5.2.7 on 2025-10-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_is_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(help_text='Informe o CPF ou CNPJ do cliente (apenas números).', max_length=18, unique=True),
        ),
    ]
