# Generated by Django 5.2.7 on 2025-12-11 02:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConjuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conjuge', models.CharField(max_length=100)),
                ('numero_rg_conjuge', models.CharField(blank=True, max_length=20)),
                ('orgao_emissor_rg_conjuge', models.CharField(blank=True, max_length=20)),
                ('documento_conjuge', models.CharField(help_text='Informe o CPF do cônjuge (somente números).', max_length=18, unique=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjuge', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('idEndereco', models.BigAutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(blank=True, max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('PB', 'Paraíba'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PB', max_length=2)),
                ('is_ativo', models.BooleanField(default=True)),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteTelefone',
            fields=[
                ('id_telefone', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')])),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('fixo', 'Fixo'), ('recado', 'Recado'), ('whatsapp', 'WhatsApp'), ('outro', 'Outro')], default='celular', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=100)),
                ('is_ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Telefone do Cliente',
                'verbose_name_plural': 'Telefones dos Clientes',
            },
        ),
    ]
