# Generated by Django 5.2.7 on 2025-12-11 02:47

from django.db import migrations, models
import re

def migrar_fones(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    ClienteTelefone = apps.get_model('clientes', 'ClienteTelefone')

    for cliente in Cliente.objects.all():
        if cliente.fone:
            numero = cliente.fone

            # Normaliza o número
            numero_limpo = re.sub(r'[^0-9]', '', numero)

            # Ignora números inválidos
            if len(numero_limpo) not in (10, 11):
                continue

            # Cria registro na tabela ClienteTelefone
            ClienteTelefone.objects.create(
                cliente=cliente,
                numero=numero,
                tipo='celular',     # pode mudar se quiser
                observacao='Migrado automaticamente',
                is_ativo=True
            )


def reverter_migracao(apps, schema_editor):
    ClienteTelefone = apps.get_model('clientes', 'ClienteTelefone')
    ClienteTelefone.objects.filter(observacao='Migrado automaticamente').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_clienteconjuge_clienteendereco_clientetelefone'),  # ajuste conforme necessário
    ]

    operations = [
        migrations.RunPython(migrar_fones, reverter_migracao),
    ]
