# Generated by Django 5.2.7 on 2025-12-11 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20251210_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular_cliente',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_cliente',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ns',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo'), ('separado_judicialmente', 'Separado judicialmente'), ('uniao_estavel', 'União estável')], default='', max_length=22),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(default='Brasileiro', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='orgao_emissor_rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='renda',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
