# Generated by Django 5.2.7 on 2025-12-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_cliente_fone_cliente_celular_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='celular_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contato_cliente',
        ),
    ]
