# Generated by Django 5.2.7 on 2025-12-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_remove_cliente_celular_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteconjuge',
            name='documento_conjuge',
            field=models.CharField(blank=True, help_text='Informe o CPF do cônjuge (somente números).', max_length=14, null=True, unique=True),
        ),
    ]
