# Generated by Django 5.2.7 on 2025-12-26 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_clienteconjuge_documento_conjuge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteendereco',
            old_name='idEndereco',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='clientetelefone',
            old_name='id_telefone',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(help_text='Informe o CPF ou CNPJ do cliente (apenas números).', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo'), ('separado_judicialmente', 'Separado judicialmente'), ('uniao_estavel', 'União estável')], default='solteiro', max_length=22),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clienteconjuge',
            name='documento_conjuge',
            field=models.CharField(blank=True, help_text='Informe o CPF do cônjuge (apenas números).', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='cep',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'CEP deve ter 8 números')]),
        ),
    ]
