# Generated by Django 5.2.7 on 2025-12-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_rename_idendereco_clienteendereco_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(help_text='Informe CPF ou CNPJ (apenas números).', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='clienteconjuge',
            name='documento_conjuge',
            field=models.CharField(blank=True, help_text='Informe CPF do cônjuge (apenas números).', max_length=14, null=True, unique=True),
        ),
    ]
