# Generated by Django 5.2.7 on 2025-12-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
