# Generated by Django 5.2.7 on 2026-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_cliente_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
