# Generated by Django 5.2.7 on 2026-01-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_alter_cliente_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(help_text='Informe CPF ou CNPJ (apenas números).', max_length=18, unique=True),
        ),
    ]
