# Generated by Django 5.2.7 on 2026-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_cliente_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
