# Generated by Django 5.2.7 on 2026-05-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_alter_cliente_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_usual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
