# Generated by Django 5.2.7 on 2026-06-08 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0024_cliente_nome_usual"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="conj_documento",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="conj_nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="conj_numero_rg",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="conj_orgao_emissor_rg",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="end_bairro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="end_cep",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "CEP deve ter 8 números"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="end_cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="end_complemento",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="end_estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PB", "Paraíba"),
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("PR", "Paraná"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="end_numero",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="end_rua",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
