# Generated by Django 5.2.7 on 2026-06-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0026_copia_dados_endereco_conjuge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clienteendereco",
            name="cliente",
        ),
        migrations.DeleteModel(
            name="ClienteConjuge",
        ),
        migrations.DeleteModel(
            name="ClienteEndereco",
        ),
    ]
