# Generated by Django 5.2.7 on 2026-06-19 16:04

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0027_remove_tabelas_endereco_conjuge"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="comprovante_residencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=clientes.models._upload_doc_cliente,
                validators=[clientes.models._validate_doc_arquivo],
                verbose_name="Comprovante de residência",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="foto_cpf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=clientes.models._upload_doc_cliente,
                validators=[clientes.models._validate_doc_arquivo],
                verbose_name="CPF",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="foto_rg_frente",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=clientes.models._upload_doc_cliente,
                validators=[clientes.models._validate_doc_arquivo],
                verbose_name="RG (frente)",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="foto_rg_verso",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=clientes.models._upload_doc_cliente,
                validators=[clientes.models._validate_doc_arquivo],
                verbose_name="RG (verso)",
            ),
        ),
    ]
