# Generated by Django 5.2.7 on 2026-06-23 00:22

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0028_cliente_comprovante_residencia_cliente_foto_cpf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="certidao_estado_civil",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=clientes.models._upload_doc_cliente,
                validators=[clientes.models._validate_doc_arquivo],
                verbose_name="Certidão de estado civil",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="conj_rg_frente",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=clientes.models._upload_doc_cliente,
                validators=[clientes.models._validate_doc_arquivo],
                verbose_name="RG cônjuge (frente)",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="conj_rg_verso",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=clientes.models._upload_doc_cliente,
                validators=[clientes.models._validate_doc_arquivo],
                verbose_name="RG cônjuge (verso)",
            ),
        ),
    ]
