# Generated by Django 5.2.7 on 2026-06-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0029_add_doc_conj_rg_certidao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RG", "RG"),
                            ("CPF", "CPF"),
                            ("CNH", "CNH"),
                            ("COMPROVANTE_ESTADO_CIVIL", "Comprovante de Estado Civil"),
                            ("COMPROVANTE_RESIDENCIA", "Comprovante de Residência"),
                            ("OUTROS", "Outros"),
                            ("CNPJ", "CNPJ"),
                            ("CONTRATO_SOCIAL", "Contrato Social"),
                            ("RG_CPF_ADMINISTRADOR", "RG / CPF do Administrador"),
                        ],
                        max_length=50,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="clientes/documentos/")),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arquivos_cliente",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Cliente",
                "verbose_name_plural": "Documentos do Cliente",
                "ordering": ["-criado_em"],
            },
        ),
    ]
