# Generated by Django 5.2.7 on 2026-06-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0030_add_cliente_documento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="certidao_estado_civil",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="comprovante_residencia",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="conj_rg_frente",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="conj_rg_verso",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="foto_cpf",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="foto_rg_frente",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="foto_rg_verso",
        ),
    ]
