# Generated by Django 5.2.7 on 2026-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0031_remove_file_fields_from_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientedocumento",
            name="status",
            field=models.CharField(
                choices=[
                    ("processando", "Processando"),
                    ("disponivel", "Disponível"),
                    ("erro", "Erro"),
                ],
                default="disponivel",
                max_length=20,
            ),
        ),
    ]
