# Generated by Django 5.2.7 on 2026-07-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0032_add_status_cliente_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientedocumento",
            name="pertence_a",
            field=models.CharField(
                choices=[("TITULAR", "Titular"), ("CONJUGE", "Cônjuge")],
                default="TITULAR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="clientedocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("RG", "RG"),
                    ("RG_NOVO", "RG Novo (com CPF)"),
                    ("CPF", "CPF"),
                    ("CNH", "CNH"),
                    ("COMPROVANTE_ESTADO_CIVIL", "Comprovante de Estado Civil"),
                    ("COMPROVANTE_RESIDENCIA", "Comprovante de Residência"),
                    ("OUTROS", "Outros"),
                    ("CNPJ", "CNPJ"),
                    ("CONTRATO_SOCIAL", "Contrato Social"),
                    ("RG_CPF_ADMINISTRADOR", "RG / CPF do Administrador"),
                ],
                max_length=50,
            ),
        ),
    ]
