# Generated by Django 5.2.7 on 2026-07-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0034_add_uuid_clientedocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="conj_nacionalidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="conj_profissao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
