# Generated by Django 5.2.7 on 2026-07-09 00:36

import clientes.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0035_cliente_conjuge_profissao_nacionalidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteRepresentante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "documento",
                    models.CharField(help_text="CPF, apenas números.", max_length=14),
                ),
                ("numero_rg", models.CharField(blank=True, max_length=20)),
                ("orgao_emissor_rg", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=200)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solteiro", "Solteiro"),
                            ("casado", "Casado"),
                            ("divorciado", "Divorciado"),
                            ("viuvo", "Viúvo"),
                            ("separado_judicialmente", "Separado judicialmente"),
                            ("uniao_estavel", "União estável"),
                        ],
                        max_length=22,
                    ),
                ),
                ("conj_nome", models.CharField(blank=True, max_length=100)),
                ("conj_numero_rg", models.CharField(blank=True, max_length=20)),
                ("conj_orgao_emissor_rg", models.CharField(blank=True, max_length=20)),
                ("conj_documento", models.CharField(blank=True, max_length=14)),
                ("is_ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representantes",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Representante do Cliente",
                "verbose_name_plural": "Representantes do Cliente",
                "ordering": ["-criado_em"],
                "unique_together": {("cliente", "documento")},
            },
        ),
        migrations.CreateModel(
            name="RepresentanteDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RG", "RG"),
                            ("CPF", "CPF"),
                            ("CNH", "CNH"),
                            ("PROCURACAO", "Procuração"),
                            ("COMPROVANTE_ESTADO_CIVIL", "Comprovante de Estado Civil"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pertence_a",
                    models.CharField(
                        choices=[("TITULAR", "Titular"), ("CONJUGE", "Cônjuge")],
                        default="TITULAR",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processando", "Processando"),
                            ("disponivel", "Disponível"),
                            ("erro", "Erro"),
                        ],
                        default="disponivel",
                        max_length=20,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="clientes/documentos_representante/",
                        validators=[
                            clientes.validators.validate_documento_representante
                        ],
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "representante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="clientes.clienterepresentante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Representante",
                "verbose_name_plural": "Documentos do Representante",
                "ordering": ["-criado_em"],
            },
        ),
    ]
