# Generated by Django 5.2.7 on 2026-07-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("clientes", "0036_clienterepresentante_representantedocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienterepresentante",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="representantes_cliente",
                to="base.endereco",
            ),
        ),
    ]
