# Generated by Django 5.2.7 on 2026-07-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0037_clienterepresentante_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representantedocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("RG", "RG"),
                    ("CPF", "CPF"),
                    ("CNH", "CNH"),
                    ("PROCURACAO", "Procuração"),
                    ("COMPROVANTE_ESTADO_CIVIL", "Comprovante de Estado Civil"),
                    ("OUTROS", "Outros"),
                    ("RG_CONJUGE", "RG do Cônjuge"),
                    ("CPF_CONJUGE", "CPF do Cônjuge"),
                    ("CNH_CONJUGE", "CNH do Cônjuge"),
                    ("CERTIDAO_CASAMENTO", "Certidão de Casamento"),
                    ("PACTO_ANTENUPCIAL", "Pacto Antenupcial"),
                ],
                max_length=50,
            ),
        ),
    ]
