# Generated by Django 5.2.7 on 2026-07-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0038_alter_representantedocumento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientedocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("RG", "RG"),
                    ("RG_NOVO", "RG Novo (com CPF)"),
                    ("CPF", "CPF"),
                    ("CNH", "CNH"),
                    ("COMPROVANTE_ESTADO_CIVIL", "Comprovante de Estado Civil"),
                    ("COMPROVANTE_RESIDENCIA", "Comprovante de Residência"),
                    ("OUTROS", "Outros"),
                    ("CNPJ", "CNPJ"),
                    ("CONTRATO_SOCIAL", "Contrato Social"),
                    ("RG_CPF_ADMINISTRADOR", "RG / CPF do Administrador"),
                    ("RG_CONJUGE", "RG do Cônjuge"),
                    ("CPF_CONJUGE", "CPF do Cônjuge"),
                    ("CNH_CONJUGE", "CNH do Cônjuge"),
                    ("CERTIDAO_CASAMENTO", "Certidão de Casamento"),
                    ("PACTO_ANTENUPCIAL", "Pacto Antenupcial"),
                ],
                max_length=50,
            ),
        ),
    ]
