# Generated by Django 5.2.7 on 2025-12-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=10)),
                ('erro', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
