# Generated by Django 5.2.7 on 2025-12-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensagemOutbox',
        ),
    ]
